manifest:
# lowest version of the manifest schema that can parse this file's data 
  version 0.8

  self:
    path: app

  projects:
    # example for a "project" that is sourced from another repository and managed by west 
    - name: doxygen-awesome
      url: https//github.com/jothepro/doxygen-awesome-css
      revision: v2.2.1
      path: deps/utilities/doxygen-awesome-css
